### ISSUE TITLE
It takes too long to predict a sentence

### ISSUE THREAD

**Issue by tnpp** [scofield7419/sequence-labeling-BiLSTM-CRF#10]
I just have a test, and produce a model use the example_datasets2. But I found it costs to long to predict, so could you please give me some messages to accelerate the prediction.

**Comment by scofield7419** [comment]
Hi, the most time-consuming part is at loading the model checkpoints. And after that, your inference will be  really very fast. Thus, you'll feel there is no wrong for the decoding speed atfer the first try.

**Comment by dfbblwd** [comment]
能否用：
convert_variables_to_constants 
进行模型固化？类似 https://www.jianshu.com/p/091415b114e2 。我是新手，也是遇到了预测速度慢的问题
