### ISSUE TITLE
checkpoint issue

### ISSUE THREAD

**Issue by hanzia** [scofield7419/sequence-labeling-BiLSTM-CRF#11]
I trained the model by using my own data,but when the time to test,means the mode = test,the program give me a problem about can't find the model,why?the train did't save the model?

**Comment by aszhanghuali** [comment]
@hanzia 您好，方便加个QQ吗？（1319466165）有几个问题想请教您！谢谢您！期待您的回复

**Comment by hanzia** [comment]
请加qq941670310------------------ 原始邮件 ------------------
发件人: "as15538191859"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 晚上9:35
收件人: "scofield7419/sequence-labeling-BiLSTM-CRF"<sequence-labeling-BiLSTM-CRF@noreply.github.com>;
抄送: "Wang weichuan"<941670310@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [scofield7419/sequence-labeling-BiLSTM-CRF] checkpoint issue(#11)



@hanzia 您好，方便加个QQ吗？（1319466165）有几个问题想请教您！谢谢您！期待您的回复
 
&mdash;
