### ISSUE TITLE
The speed of prediction is slow

### ISSUE THREAD

**Issue by YijianLiu** [scofield7419/sequence-labeling-BiLSTM-CRF#27]
It takes at least 5mins to load vocab and dataManager, the prediction is too slow and I try to make CUDA_VISIBLE_DEVICES=1 but it doesn't use CUDA to extract entity, I want to know why and I make sure I have successfully configure CUDA for tensorflow-gpu.

**Comment by Hasebe17** [comment]
同问，这速度慢成乌龟了
