### ISSUE TITLE
Divide by Zero error in engines/BiLSTM_CRF

### ISSUE THREAD

**Issue by prdatta001** [scofield7419/sequence-labeling-BiLSTM-CRF#28]
I have been trying to use the code on my own data. I followed the instructions and changed the sytem.config file accordingly. However, when I train the model, I keep getting the following DividebyZero error:

`File "/sequence-labeling-BiLSTM/engines/BiLSTM_CRFs.py", line 302, in train
    val_results[k] /= num_val_iterations
ZeroDivisionError: division by zero
`

**Comment by zhijie-yan** [comment]
check your dataset
